config/routes.rb
Lunches::Application.routes.draw do
  get "lunch/index/"
  root :to => "lunch#index"

  resources :users
  resources :foods
  resources :soups
  resource :session

  match '/:date' => "lunch#index", :constraints => { :date => /\d{4}-\d{1,2}-\d{1,2}/ }

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  match 'settings' => 'users#edit', :as => :settings, :via => :get

  match 'lunch/add_soup/:id' => 'lunch#add_soup'
  match 'lunch/remove_soup/:id' => 'lunch#remove_soup'

  match 'lunch/add_food/:id' => 'lunch#add_food'
  match 'lunch/remove_food/:id' => 'lunch#remove_food'
  #match 'remove_favourite_soup' => 'lunch#remove_soup/:id', :as => :remove_favourite_soup

  match ':controller(/:action(/:id(.format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta property="og:locale" content="sk_SK" />
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="lunches.guitarman.sk"/>
  <meta property="og:description" content="guitarman: lunches"/>
  <meta name="author" content="all: guitarman" />
  <title>Lunches</title>
  <%= stylesheet_link_tag "lunch", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Marvel' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <script>
//     fading out of notice, sliding up and removing from DOM
    setTimeout(function() {
        $('.notice').fadeTo(800, 0.00, function(){
            $(this).slideUp(800, function(){
                $(this).remove()
            })
        })
    }, 6000);
  </script>
</head>
<body>
    <div id="container" class="container">
      <div id="header" class="header">
        <div id="h_content" class="h_content">
		  <span class="caption">
          	<%= link_to "obedy [beta]", root_path %>
		  </span>
		  <span class="user_nav">
			<% if logged_in? %>
				<%= link_to current_user.email, settings_path, :title => "Upraviť profil" %>
                | <%= link_to "Odhlásiť", logout_path, :title => "Odhlásiť sa" %>
			<% else %>
				<%= link_to "Prihlásiť", login_path, :title => "Prihlásiť sa" %>
                | <%= link_to "Registrovať", new_user_path, :title => "Registrovať sa" %>
			<% end %>
		  </span>
        </div>
      </div>

      <div id="content_container" class="content_container">
        <div id="content" class="content">
          <div class="flash_message">
            <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
            <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
          </div>

          <%= yield %>
          <br/>
        </div>
		<div id="footer" class="footer">
          <a href="http://guitarman.sk" target="_blank">guitarman.sk</a> <%=Time.now.year%> | Subpages: <a href="http://lunch.guitarman.sk" target="_blank">lunch.guitarman.sk</a> | Contact: guitarman[at]guitarman.sk
		</div>
      </div>
      <br />
    </div>
</body>
</html>